# baseurl = "https://www.aptly.info/"
baseurl = "http://aptly-dev.github.io/www.aptly.info/"
languageCode = "en-us"
title = "Debian repository management tool"

[params]
    DisqusShortname = "aptly"

[author]
    name = "Andrey Smirnov"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
